language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - 'nvm install-latest-npm'
sudo: false
arch:
  - amd64
  - ppc64le
matrix:
    exclude:
         - node_js: "iojs"
           arch: ppc64le
         - node_js: "0.12"
           arch: ppc64le
         - node_js: "0.10"
           arch: ppc64le
         - node_js: "0.8"
           arch: ppc64le
